# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: "cargo build"

on:
    workflow_dispatch:
        inputs:
            repository:
                type: "string"
                description: "Repository: username/project"
                required: true

permissions:
    contents: "read"

concurrency:
    group: "${{ github.workflow }}-${{ github.ref }}"
    cancel-in-progress: true

jobs:
    cargo_build:
        name: "cargo build - ${{ inputs.repository }}"
        runs-on: "ubuntu-22.04"
        timeout-minutes: 10
        steps:
        -
            name: "Checkout repository"
            uses: "actions/checkout@v4"
            with:
                repository: "${{ inputs.repository }}"
        -
            name: "Install Rust Toolchain"
            uses: "dtolnay/rust-toolchain@stable"
            with:
                toolchain: "stable"
        -
            name: "Build bin"
            run: |
                cargo build --verbose --bins --release
        -
            name: "Strip binaries"
            run: |
                find target/release/ -maxdepth 1 -type f -executable -exec strip --strip-all target/release/dns-ptr-resolver '{}' ';'
        -
            name: "Upload artifacts"
            uses: "actions/upload-artifact@v4"
            with:
                name: "${{ inputs.repository }}-binaries"
                path: "target/release/"
                if-no-files-found: "error"
