# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: "cargo build"

on:
    workflow_dispatch:
        inputs:
            repository:
                type: "string"
                description: "Repository: username/project"
                required: true

permissions:
    contents: "read"

concurrency:
    group: "${{ github.workflow }}-${{ github.ref }}"
    cancel-in-progress: true

jobs:
    cargo_build:
        name: "cargo build - ${{ inputs.repository }}"
        runs-on: "ubuntu-22.04"
        timeout-minutes: 10
        steps:
        -
            name: "Checkout repository"
            uses: "actions/checkout@v4"
            with:
                repository: "${{ inputs.repository }}"
        -
            name: "Install Rust Toolchain"
            uses: "dtolnay/rust-toolchain@stable"
            with:
                toolchain: "stable"
        -
            name: "Build bin"
            run: |
                cargo build --verbose --release
        -
            name: "DEBUG"
            run: |
                find . -type f
